data:
  train_path: "data/train_u6lujuX_CVtuZ9i.csv"
  test_path: "data/test_Y3wMUE5_7gLdaTN.csv"

training:
  test_size: 0.2
  random_state: 42

model:
  save_path: "models/final_model.pkl"
  model_dir: "models/"
